config/routes.rb
Recapitulator::Application.routes.draw do
  devise_for :users

  root :to => 'open_pages#index'
  
  resources :teachers
  resources :students
  

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :text, :right_answer

  belongs_to :question

  validates :text, :presence => true
end

app/models/course.rb
class Course < ActiveRecord::Base
  attr_accessible :title, :lessons, :users

  has_many    :scores
  has_many    :lessons

  has_and_belongs_to_many :users
  belongs_to  :grade_of_school
  

end

app/models/grade_of_school.rb
class GradeOfSchool < ActiveRecord::Base
  attr_accessible :name, :start_date, :end_date
  
  before_save :default_values

  has_many :users
  has_many :courses
  belongs_to :school

  def default_values
    date = Date.today
    self.start_date ||= date
    self.end_date ||= date.change(:year => date.year + 1)
  end
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  attr_accessible :title, :date, :number_of_answers
  
  before_save :default_values

  has_many :objectives
  has_many :questions
  has_many :scores

  belongs_to :course
  
  MAX_ANSWERS = 10
  
  def default_values
    self.date ||= Date.now
  end

end

app/models/objective.rb
class Objective < ActiveRecord::Base
  attr_accessible :text

  belongs_to :lesson

end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :text, :mistake_type, :awesome
  before_save :number_of_answers

  has_many :answers

  belongs_to :user
  belongs_to :lesson
  
  MISTAKE_TYPES = {
    :no_mistakes => 0,
    :spelling_mistake => 1,
    :fact_mistake => 2,
    :spelling_fact_mistake => 3
  }.freeze
  
  def number_of_answers
    self.number_answers ||= self.lesson.number_of_answers
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :title

  has_many :user

end

app/models/school.rb
class School < ActiveRecord::Base
  attr_accessible :name, :location, :country, :url

  has_many :users
  has_many :grades_of_schools

  validates :url, :presence => true, :uniqueness => true
  validates :name, :presence => true
end

app/models/score.rb
class Score < ActiveRecord::Base
  attr_accessible :points, :max_points

  belongs_to :lesson
  belongs_to :user
  belongs_to :course
  
  # def self.all_score_user(u_id, c_id)
  #   user_points = self.find(:points).where("user_id = ? and course_id = ?", [u_id, c_id]).inject { |sum, i| sum + i }
  #   all_max_points = self.find(:max_points).where("user_id = ? and course_id = ?", [u_id, c_id]).inject { |sum, i| sum + i }
  #   "#{user_points}/#{all_max_points}"
  # end
  # 
  # def self.lesson_score_user(u_id, l_id)
  #   user_points = self.find(:points).where("user_id = ? and lesson_id = ?", [u_id, l_id])
  #   "#{user_points.first}/#{max_points}"
  # end
  # 
  # def self.lesson_average_scores(l_id)
  #   user_points = self.find(:points).where("lesson_id = ?", l_id)
  #   num_students = user_points.length
  #   average_user_points = user_points.inject { |sum, i| sum + i } / num_students
  #   "#{average_user_points}/#{all_max_points}"
  # end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :username, :courses
  # attr_accessible :name, :email, :password, :password_confirmation
  

  has_many    :questions
  has_many    :scores

  has_and_belongs_to_many :courses
  
  belongs_to  :school
  belongs_to  :role
  belongs_to  :grade_of_school

  # has_secure_password
  validates :password, :presence => { :on => :create }

  validates :name, presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  
  validates :username, presence: true, length: { maximum: 20 }
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/open_pages_controller.rb
class OpenPagesController < ApplicationController

  def index
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_filter :authenticate_user!
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @user = User.find(current_user)
    @courses = Course.find_by_user_id(current_user)
  end
  
  def show
    # @teacher = User.find(current_user.id)
    @course = Course.find(params[:c_id])
    @lessons = Lesson.where(["course_id = ?", @course.id])
  end
  
  def new 
    case params[:name] 
    when "course" 
      @course = Course.new
      @course.users << current_user
    when "lesson" 
      @date_today = Date.today
      @answer_range = (1..MAX_ANSWERS).to_a
      @lesson = Lesson.new
      @lesson.course_id = params[:c_id]
    end
  end
  
  def create
    case params[:name] 
    when "course"
      @course = Course.new params[:course]
      @course.save
    when "lesson" 
      @lesson = Lesson.new params[:lesson]
      @lesson.save
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def full_title(title = "")
    base_title = "The-Anchor-Effect"
    if title.empty?
      base_title
    else
      "#{base_title}: #{title}"
    end
  end
end

app/views/layouts/_flash_message.html.erb
<div class="flash_message">
	<% flash.each do |name, msg| %>
	  <%= content_tag :div, msg, id: "flash_#{name}" %>
	<% end %>
</div>

app/views/layouts/_footer.html.erb
(c) Daniela Grossmann, SF 2012

app/views/layouts/_header.html.erb
<h1><%= full_title %></h1>

<%= render 'layouts/user_login' %>

app/views/layouts/_ie_message.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_user_login.html.erb
<ul id="user_nav">
  <% if user_signed_in? %>
    Logged in as <strong><%= current_user.username %></strong>.
    <li><%= link_to 'Edit profile', edit_user_registration_path %> | </li>
    <li><%= link_to "Logout", destroy_user_session_path, method: :delete %> </li>
  <% else %>
    <li><%= link_to "Sign up", new_user_registration_path %> |</li>
    <li><%= link_to "Login", new_user_session_path %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
	<%= 'layouts/ie_message' %>
</head>
<body>
	<header class="header_footer">
		<%= render "layouts/header" %>
	</header>
	
	<div id="wrapper">
		<div id="content">
			<h2><%= yield(:heading) %></h2>
			<%= render 'layouts/flash_message' %>
			
			<%= yield %>
			
		</div>
	</div>
	
	<footer class="header_footer">
		<%= render "layouts/footer" %>
	</footer>
	
</body>
</html>

app/views/open_pages/index.html.erb
<% provide(:title, "") %>
<% provide(:heading, "Welcome!") %>

Welcome to the Recapitulator!

app/views/students/_form_for_question.html.erb
<%= form_for(@question) do |f| %>
  <div class="field">
		<%= f.label :text %><br />
  	<%= f.text_area :text %>
	</div>
  
<% end %>

app/views/users/_form_course.html.erb
<%= form_for(@course, :url => teachers_path) do |f| %>

  <div class="field">
		<%= f.label :title %><br />
  	<%= f.text_field :title %>
	</div>

	<div><%= f.submit %></div>
	
<% end %>

app/views/users/_form_lesson.html.erb
<%= form_for(@lesson, :url => teachers_path) do |f| %>

  <div class="field">
		<%= f.label :title %><br />
  	<%= f.text_field :title %>
	</div>

  <div class="field">
	  <%= f.label :date %><br />
		<%= date_select("lesson", "date", :use_month_numbers => true,  :start_year => date_today.year,
								:prompt => { :day => 'Select day', :month => 'Select month', :year => 'Select year' },
								:field_name => "Held on:") %>
	</div>
	
	<div class="field">
		<%= f.label :number_of_answers %><br />
		<%= f.collection_select(:lesson, :number_of_answers, @answer_range) %>
	</div>
	
	<div><%= f.submit %></div>
<% end %>

<!-- LATER: number of answers, sick students -->

app/views/users/index.html.erb
<% provide(:title, "Teacher") %>
<% provide(:heading, "Welcome, #{@teacher.name}!") %>

<%= link_to "new course", new_teacher_path(:name => 'course') %>


<% unless @courses.blank? %>
	<p>All courses:</p>
	<ul>
		<% @courses.each do |course| %>
		<li><%= link_to course.title, teacher_path(:c_id => course.id) %></li>
		<% end %>
	</ul>
<% end %>

app/views/users/new.html.erb
<% provide(:title, "New #{params[:name]}") %>
<% provide(:heading, "New #{params[:name]}") %>

<%= render "form_#{params[:name]}" %>

app/views/users/show.html.erb
<% provide(:title, "Teacher(#{@course.title})") %>
<% provide(:heading, "Course: #{@course.title}") %>

<%= link_to "new lesson", new_teacher_path(:name => 'lesson', :c_id => params[:c_id]) %>

<p>Lessons:</p>
<ul>
<%  @lessons.each do |lesson| %>
	<li><%= link_to lesson, "#" %></li>
<% end %>
</ul>